#!/usr/bin/env bash
#
# PreToolUse hook (Bash): blocks `git commit` when text claiming AI authorship
# appears in the staged diff or the commit message. Enforces the
# confidentiality rule from CLAUDE.md.
#
# The repo is public and may freely mention AI / LLM tools as external tools
# an operator uses (e.g. for the manual-override authoring workflow). What
# this hook blocks is text that suggests the *code itself* was authored by
# an AI assistant — commit trailers, "generated by", emoji markers, etc.
#
# Exit 2 = blocked; stderr is returned to the agent so it can fix the issue.
#
set -uo pipefail

cmd=$(jq -r '.tool_input.command // empty')

case "$cmd" in
  *"git commit"*) ;;
  *) exit 0 ;;
esac

pattern='(generated|written|authored|created) (by|with|using) (claude|anthropic|copilot|chatgpt|openai|gemini|gpt|llm|\bai\b)'
pattern="$pattern"'|co-authored-by:[[:space:]]*(claude|anthropic|copilot|chatgpt|openai|gemini)'
pattern="$pattern"'|(claude|gpt|llm|\bai\b)-generated'
pattern="$pattern"'|🤖.*(generated|created|written|by)'

hits=$(
  {
    # Skip the files that *define* the rule — their content quotes the
    # forbidden patterns as documentation and would always match itself.
    git diff --cached \
      -- . \
      ':!.claude/CLAUDE.md' \
      ':!.claude/hooks/confidentiality-check.sh' \
      2>/dev/null | grep -E '^\+' | grep -vE '^\+\+\+' || true
    printf '%s\n' "$cmd"
  } | grep -niE "$pattern" || true
)

if [ -n "$hits" ]; then
  {
    echo "Confidentiality check failed — staged commit claims AI authorship:"
    echo "$hits"
    echo
    echo "Remove any 'generated/written/authored by <tool>', AI co-author"
    echo "trailers, or '🤖' markers (see CLAUDE.md > Confidentiality)."
  } >&2
  exit 2
fi

exit 0
